base {
  ##### PROMPTING MODEL #####
  "reasoning_model" = "gemma4:31b-it-bf16" # "nemotron-3-nano:30b-a3b-fp16" # "deepseek-r1:70b-llama-distill-q4_K_M"
  "output_model" = "gemma3:4b"
  "cluster_model" = "sentence-transformers/all-MiniLM-L6-v2"
  "pretrained_model" = "roberta-base"
  "seed" = 42
  "temperature" = 1.0
  "top_p" = 0.95
  "top_k" = 64
  "num_ctx" = 14336
  "think" = true
  "event_chain_num_threshold" = 30
}

reddit = ${base}{
  ##### DATA #####
  "output_path" = "./data/reddit/"
  "relations_path" = "./data/reddit/reddit_processed_corpus_relations_2000.pkl"
  "event_chains_path" = "./data/reddit/reddit_event_chains.pickle"
  "char_event_chains_path" = "./data/reddit/reddit_char_event_chains.pickle"
}

reddit_parkinsons = ${base}{
  ##### DATA #####

  ##### Pre-Preprocessing #####
  "output_path" = "./data/reddit/parkinsons/"
  "corpus_path" = "./data/reddit/parkinsons/processed_corpus.json"

  ##### Sampling #####
  "sampled_corpus_path" = "./data/reddit/parkinsons/sampled_corpus.json"

  ##### Generate Event Pairs from Sampled Corpus #####
  "event_pairs_path" = "./data/reddit/parkinsons/event_pairs.pickle"

  "causal_annotations_path" = "./data/reddit/parkinsons/causal_annotations.pickle"
  "causal_verbalizations_path" = "./data/reddit/parkinsons/causal_verbalizations.pickle"
}

reddit_longcovid = ${base}{
  ##### DATA #####

  ##### Pre-Preprocessing #####
  "output_path" = "./data/reddit/longcovid/"
  "corpus_path" = "./data/reddit/longcovid/processed_corpus.json"

  ##### Sampling #####
  "sampled_corpus_path" = "./data/reddit/longcovid/sampled_corpus.json"

  ##### Generate Event Pairs from Sampled Corpus #####
  "event_pairs_path" = "./data/reddit/longcovid/event_pairs.pickle"

  "causal_annotations_path" = "./data/reddit/longcovid/causal_annotations.pickle"
  "causal_verbalizations_path" = "./data/reddit/longcovid/causal_verbalizations.pickle"
}

reddit_covid_vaccinated = ${base}{
  ##### DATA #####

  ##### Pre-Preprocessing #####
  "output_path" = "./data/reddit/covid_vaccinated/"
  "corpus_path" = "./data/reddit/covid_vaccinated/processed_corpus.json"

  ##### Sampling #####
  "sampled_corpus_path" = "./data/reddit/covid_vaccinated/sampled_corpus.json"

  ##### Generate Event Pairs from Sampled Corpus #####
  "event_pairs_path" = "./data/reddit/covid_vaccinated/event_pairs.pickle"

  "causal_annotations_path" = "./data/reddit/covid_vaccinated/causal_annotations.pickle"
  "causal_verbalizations_path" = "./data/reddit/covid_vaccinated/causal_verbalizations.pickle"
}