base {
  ##### MODEL #####
  "reasoning_model" = "deepseek-r1:70b-llama-distill-q4_K_M"
  "output_model" = "gemma3:4b"
  "cluster_model" = "sentence-transformers/all-MiniLM-L6-v2"
  "seed" = 42
  "temperature" = 0.0
}

mfc_immigration = ${base}{
  ##### DATA #####
  "output_path" = "./data/mfc/immigration/"
  "relations_path" = "./data/mfc/immigration/mfc_immigration_processed_corpus_relations_2000.pkl"
  "event_chains_path" = "./data/mfc/immigration/mfc_immigration_event_chains.pickle"
  "annotated_event_chains_path" = "./data/mfc/immigration/mfc_immigration_annotated_event_chains.pickle"
}

guncontrol = ${base}{
  ##### DATA #####
  "data_path" = "./data/guncontrol/guncontrol_corpus_relations.pickle"
  "doc_keys_path" = "./data/guncontrol/doc_keys.pickle"
  "split_range" = [0, 2000]
  "output_path" = "./data/guncontrol/"
  "relations_path" = "./data/guncontrol/guncontrol_event_chains_"
  "event_chains_path" = "./data/guncontrol/guncontrol_event_chains_cleaned.pickle"
  "embedding_path" = "./data/guncontrol/guncontrol_event_chains_embs_non_expansion.pickle"
  "clusters_path" = "./data/guncontrol/kmeans_clusters_"
  "cluster_embs_path" = "./data/guncontrol/embeddings.pickle"

  ##### CLUSTERING #####
  "cluster_keyphrase" = false
  "top_25" = true
  "num_clusters" = [200]   # [25, 50, 75, 100, 125, 150, 175, 200]
  "cluster_feats" = false
  "batch_size" = 32
  "lr" = 2e-5
  "epochs" = 25
  "num_classes" = 14

  ##### LDA #####
  "num_iterations" = 1000
}