base {
  ##### MODEL #####
  "model" = "meta-llama/Meta-Llama-3.1-8B-Instruct"
  "cluster_model" = "sentence-transformers/all-MiniLM-L6-v2"
  "seed" = 42
  "dataset_seed" = 42
  "max_tokens" = 4096
  "temperature" = 0.1
  "pretrained_model" = "roberta-base"
}

immigration = ${base}{
  ##### DATA #####
  "data_path" = "./data/immigration/immigration_corpus_wnu_relations.pickle"
  "doc_keys_path" = "./data/immigration/doc_keys.pickle"
  "split_range" = [0, 2000]
  "output_path" = "./data/immigration/"
  "relations_path" = "./data/immigration/immigration_event_chains_"
  "event_chains_path" = "./data/immigration/immigration_event_chains_cleaned.pickle"
  "embedding_path" = "./data/immigration/immigration_event_chains_embs_non_expansion.pickle"
  "clusters_path" = "./data/immigration/"
  "cluster_embs_path" = "./data/immigration/embeddings.pickle"
  "annotated_event_chains_path" = "./data/immigration/annotated_event_chains.pickle"
  "grid_search_path" = "./data/immigration/grid_search_results.json"

  ##### CLUSTERING #####
  "cluster_keyphrase" = false
  "top_25" = false
  "num_clusters" = [200]   # [25, 50, 75, 100, 125, 150, 175, 200]
  "batch_size" = 32
  "lr" = 2e-5
  "epochs" = 25
  "num_classes" = 15

  ##### LDA #####
  "num_iterations" = 1000
}

guncontrol = ${base}{
  ##### DATA #####
  "data_path" = "./data/guncontrol/guncontrol_corpus_relations.pickle"
  "doc_keys_path" = "./data/guncontrol/doc_keys.pickle"
  "split_range" = [0, 2000]
  "output_path" = "./data/guncontrol/"
  "relations_path" = "./data/guncontrol/guncontrol_event_chains_"
  "event_chains_path" = "./data/guncontrol/guncontrol_event_chains_cleaned.pickle"
  "embedding_path" = "./data/guncontrol/guncontrol_event_chains_embs_non_expansion.pickle"
  "clusters_path" = "./data/guncontrol/kmeans_clusters_"
  "cluster_embs_path" = "./data/guncontrol/embeddings.pickle"

  ##### CLUSTERING #####
  "cluster_keyphrase" = false
  "top_25" = true
  "num_clusters" = [200]   # [25, 50, 75, 100, 125, 150, 175, 200]
  "cluster_feats" = false
  "batch_size" = 32
  "lr" = 2e-5
  "epochs" = 25
  "num_classes" = 14

  ##### LDA #####
  "num_iterations" = 1000
}